import os

# --- Coin & Timeframe Settings ---
COINS = [
    "BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT", "MATICUSDT",
    "ADAUSDT", "XRPUSDT", "DOGEUSDT", "DOTUSDT", "AVAXUSDT",
    "LTCUSDT", "TRXUSDT", "LINKUSDT", "ATOMUSDT", "NEARUSDT",
    "UNIUSDT", "FILUSDT", "AAVEUSDT", "ETCUSDT", "INJUSDT",
    "OPUSDT", "RUNEUSDT", "SANDUSDT", "APTUSDT", "HBARUSDT"
]
INTERVALS = ["5m", "15m", "1h", "1d"]
CANDLE_LIMIT = 100
CHECK_INTERVAL_SECONDS = 900

# --- Telegram Credentials from Env ---
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")
