services:
  - type: worker
    name: crypto-signal-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TELEGRAM_TOKEN
        fromEnvVar: TELEGRAM_TOKEN
      - key: CHAT_ID
        fromEnvVar: CHAT_ID
